### ISSUE TITLE
More detailed documentation!

### ISSUE THREAD

**Issue by csetom** [arnonram/swade-npc-importer#110]
**The Problem:** I was having a hard time, to understand the working of this modul, especial the bullet points, and the modified specail abilities. I am still learning it, but I have to see the source code to understand, how my imported NPC needed to look like.

**For more detail**: I wanted to import from The After PDF but the Special Abilities didn't work. Neither do tfrom he Savaged.us bestary.

**Solution:** So I think a more detailed version of the documentation will help anybody. You just need to show us some examples, and explain, which option do what exsacly, and how to use them.

**Comment by SalieriC** [comment]
While a documentation would be beneficial, in all honesty and fairness I feel the need to say that the `The After` bestiary is terribly formatted. A great setting and a great bestiary, but brimming with formatting errors. lots of dots and semicolons in the wrong places. I had to edit it quite a bit.

**Comment by csetom** [comment]
> 
Yes, it is, but my bigger problem is, I tried every possible logical way to make it work, until i gave up, and looked the source code, how its parse the special abilities. And I still have problems why sometimes do nothing, and sometimes get an error, or parse badly.

**Comment by arnonram** [comment]
Hi @csetom 
Documentation is the bane of many developers... we know it's important but can't be buggered to make it very good (in most cases) ;)

The importer was built to work with the [official way Pinnacle recommends writing stat-blocks](https://peginc.com/about/writing-for-pinnacle/), because trying to parse all ways stat-blocks are written is madness... (it could probably be done with some machine learning, but that's out of my league at the moment) :)

i'll see about trying to improve the docs. In the meantime, if we are talking about using the `modified special abilities` feature here's a sample:
```
Some Monster
Stuff about the monster. Lots of it..
Attributes: Agility d8, Smarts d6, Spirit d6,
Strength d10, Vigor d10
Skills: Athletics d6, Fighting d8, Notice d6,
Shooting d8, Stealth d8
Pace: 6; Parry: 6; Toughness: 7
Edges: Combat Reflexes
Special Abilities:
@sa Aquatic: Pace 12″.
@e Burrow (10″): Some Monsters can meld
into and out of the ground
@e Immunity: Immune to water-based attacks.
@w Slam: Str+d6, nonlethal damage.
@a Armor +2
@h Weakness(dirt): Some Monster hate being dirty
@e Size +6: This one is rather large-ish
@e Fear (-2): boo
@e Poison(2): ahhhh!
@sa SpecialAbs: this is a ver special Abilitiy
```
