### ISSUE TITLE
Armor, Weapons and Gear do not copy properly

### ISSUE THREAD

**Issue by efadfa3** [arnonram/swade-npc-importer#141]
```
Aisha
Novice Female Changed, Healthcare Professional(tm)

Attributes: Agility d4, Smarts d6, Spirit d4, Strength d12, Vigor d6
Skills: Athletics d4, Common Knowledge d4, Fighting d6, Healing d6, Intimidation d4, Notice d4, Shooting d10, Stealth d4, Survival d6
Pace: 6; Parry: 5; Toughness: 11 (6)
Hindrances: Loyal, Outsider (minor, ), Secret (major, Killed her husband, cut him into pieces using her medical knowledge and then diffused him in a bathtub. No body, no crime.), Unstable System (minor)
Armor: Bandana (Armor 1), Bronze Arm Guards (vambraces) (Armor 3), Kevlar Riding Jeans (Armor 2), Kevlar helmet (Armor 4), Kevlar vest with ceramic inserts (2008+ military issue) (Armor 6)
Weapons: Unarmed (Range Melee, Damage Str), KSG 12 (Range 12/24/48, Damage (1-3)d6, ROF 1), Mace/Warhammer (Range Melee, Damage Str+d6)
Gear: Backpack (Contains: 2x Lantern, 5x Oil (1 pint), Medic Kit, 100x Shotgun slug, Crowbar, 2x Blanket, 2x Firestarting Kit, 5x Soap, Bedroll (sleeping bag; winterized), Brass Knuckles), Boots, Hiking, Canteen (Contains: Restaurant, Cheap), Clothing, normal, 10x Shotgun slugs, Winter Gear (cloak/parka)
Current Wealth: $23
Special Abilities
Bio-Acceptance: -2 penalty to resist any effects caused by Butchertech or Breach energy, including the effects of the Boon.
Branded: Draw two cards and consult the Cosmetic Changes table for each draw.
The New Flesh: Choose one entry from the Major Anomaly Table and two entries from the Minor Anomaly Table.
Not Like Us: Suffer from the Outsider (Minor) Hindrance.
Languages Known:
Current Load: 94.6 (101)
Books In Use: Savage Worlds: Adventure Edition, The After
Setting Rules: Cyberware Tab
Validity: Character appears valid and optimal
```

^this is the stat block I exported from savaged.us. I tried to put it into foundry, but "Armor" and "Weapons" keep being listed in Hindrances like this:
![image](https://github.com/arnonram/swade-npc-importer/assets/47500889/716699e4-4a30-402b-ad5f-aa24d954b527)
I tried to add or remove custom names like KSG instead the Street Sweeper and the entire Bandana, removing descriptions of hindrances and trying to keep everything as vanilla as possible, moving Armor and Weapons to be AFTER Gear or just straight up inside it - nothing appears in Gear. Just Backpack. Everything else is in Hindrances (in the original stat block) or just straight up gone (after I moved stuff into Gear, for example). 

I did do the insecure origins thing, to no avail. I checked "Character" in the thing.  I'm out of ideas.

**Comment by SalieriC** [comment]
Should be because they are under Hindrances. The importer doesn't look for `Armor:` or `Weapons:` but for `Gear:` as this is how it is structured in standard stat blocks. You'll need to manually edit the stat block to fit a standard stat block. In other words: The module is intended to be used with print media, Savaged.us is not a print media and structures things differently. For example I would also remove the line with current load. That's why there was a Savaged.us importer but I think it has been abandoned.
You'll likely experience other issues as well but that has to do with the way item sheets changed since the last update of the NPC Importer. It will need some work to accommodate those changes but don't keep your hopes up that those will be fixed soon. I know him a bit and can assure you that it is not by choice. That said, the importer generally still works fine, it just always requires a bit of work and knowledge about how the system handles things. I recently imported the lot of All for One and the NPC importer still saved me quite a bit of time. The best advice I can give atm is: Import stats and set up weapons, armor and gear yourself.
