### ISSUE TITLE
Improved handling of pre-swade statblocks

### ISSUE THREAD

**Issue by eXaminator** [arnonram/swade-npc-importer#36]
It would be great if the imported could improve handling for some older stat blocks.

Some points of the top of my head:
- Charisma should be ignored (or added as a modifier to Persuasion etc.)
- Skills could be updated to newer versions (like Throwing, Climbing and Swimming could automatically be replaced by Athletics)
- Knowledge Skills could try some sort of best effort to be replaced by appropriate other skill (this might be hard...)

**Comment by SalieriC** [comment]
I think this is currently very unrealistic. There are no official general statements on how to do this, basically all PEG settings with conversions have their way of converting them and non-PEG settings might have others if at all. Also there is the problem with adding core skills. The importer has no way of knowing which ones to add on which NPC (not all creatures get all core skills but some should gain them if not present). Then how to determine which skill to use as the new skill i.e. on Athletics is also not 100% clear. I think the best bet currently is to adjust NPCs manually and then importing them. Everything automated is bound to be messy imo.

**Comment by eXaminator** [comment]
I disagree (partially).

1. I guess as charisma is just based on edges etc., it would be sufficiant to just ignore it (as the character will probably have the edges anyways). But currently it is parsed as part of the last skill, which should be changed.
2. I think this one is actually simple, as it is mostly straight forward (like my example) and not really setting specific (unless they introduce custom skills, but than again: just make this optional).
3. I agree that it is probably impossible to find a good cross-setting solution for knowledge skills.

**Comment by SalieriC** [comment]
> I disagree (partially).
You are free to do so. =)

> 1. I guess as charisma is just based on edges etc., it would be sufficiant to just ignore it (as the character will probably have the edges anyways). But currently it is parsed as part of the last skill, which should be changed.
Charisma is the easiest. Either have it in the setting configurator which the Importer can handle already or ignore it. Adding modifiers to Persuasion is not an option in my book as the modifiers depend on role play like the looks of an attractive woman maybe don't matter on a saurian beast race.
> 2. I think this one is actually simple, as it is mostly straight forward (like my example) and not really setting specific (unless they introduce custom skills, but than again: just make this optional).
Swimming d4-2 (not present); Throwing d6; Climbing d12
So, which die should the importer pick? Always the highest? What about Swimming then, which the creature clearly can not. Always the middle value? What about Climbing then at which the creature is excellant? Always the lowest? Same.
PEG gives suggestions on how to handle this **per setting**, not in general. And this is the problem here.
And also what I already said: The importer has no way of knowing where to add missing core skills and which to add. An Assassin might had no Persuasion in SWDX but in SWADE he has at least a d4 while a giraffe had no Persuasion and won't get it.

In any case, even if there were a general way to handle this it should be toggleable as some might want to import pre SWADE stats as is.

**Comment by arnonram** [comment]
@eXaminator you're asking here for an SWDX -> SWADE converter, which is rather outside the scope of this here module.

As @SalieriC said... it's not a straight conversion and is mostly decided on a case by case for each npc/character by the GM.

I'm sorry, but I'll have disappoint you on this one as it's not something I really want to get into

**Comment by eXaminator** [comment]
Ok, I understand that

I also managed to teach it to handle Charisma as an additional stat, which at least prevents the skill import from breaking. Though I found some other bugs / edge cases I might open bugs for.
