### ISSUE TITLE
Importer does not use predefined Special Ability on import

### ISSUE THREAD

**Issue by SalieriC** [arnonram/swade-npc-importer#73]
Similar to #32 now with Special Ability. It does not use the predefined item "Size" when importing something like `Size 1`. This is possibly true for other special abilities as well.

**Comment by SalieriC** [comment]
Yeah, it's true for everything with any additional stuff behind the actual name set up like Burrow which usually comes with the burrowing pace in parenthesis in the name.

**Comment by SalieriC** [comment]
I think this is related: Edges are a problem as well. Although this might be an edge case which only applies to me: I like to set up my Edges using `(Imp)` at the end (as seen in official stat blocks) for alphabetical sorting. The importer does not use those predefined items as well, creating new ones. But maybe this case is too special?

**Comment by SalieriC** [comment]
Oh and just noticed: The Importer also has trouble with multiple spaces. So `Combat  Reflexes` (mind the double space) would not use the predefined item. This is a very common thing when copying stat blocks from PDFs.

**Comment by arnonram** [comment]
> I think this is related: Edges are a problem as well. Although this might be an edge case which only applies to me: I like to set up my Edges using `(Imp)` at the end (as seen in official stat blocks) for alphabetical sorting. The importer does not use those predefined items as well, creating new ones. But maybe this case is too special?

The fix i did was a more general fix for all items, so should handle Edges/Hindrances/Gear/Special Abilities/etc..:
1. Search for the item in compendiums as it appears. So for example _Burrow (5")_ ==> if nothing found go to 2
2. Search for item up to the parenthesis. So: _Burrow_, ==> if nothing found Create item for Actor

Regarding the `(Imp)`: the importer changes the Imp to Improved and moves it to the start of the name, so Block (Imp) ==> Improved Block (this is how it's written in the official books). The (Imp) is only for statblocks.
BUT, the above fix should solve your issue as well (since i'm first searching for the complete name as it came form the statblock)
