### ISSUE TITLE
Import Ranged Weapons Failing

### ISSUE THREAD

**Issue by stgreenb** [arnonram/swade-npc-importer#77]
Thank you for your work on this tool. 
Below is an example of an NPC pulled from the [Titan Effect RPG Jump Start.](https://titaneffect.com/wp-content/uploads/2019/08/KEM_TitanEffect_JumpStart.pdf) I am able to get most of the stats to import but it seems to fail on any ranged weapons. Since I am coping them to a text editor anyway, is there a modification I can make prior to import so that they will come through? 

ARES Black Ops Operator
They are highly trained soldiers working for ARES clandestine division, the Phobos Unit. There are 2 ARES operators for each operative.
Attributes: Agility d6, Smarts d6, Spirit d8, Strength d8, Vigor d8
Skills: Athletics d6, Common Knowledge d6, Battle d6, Driving d6, Fighting d8, Intimidation d6, Notice d8, Piloting d6, Shooting d8, Stealth d6
Pace: 6; Parry: 6; Toughness: 12 (6)
Hindrances: Obligations (to ARES)
Edges: Combat Reflexes, Soldier
Gear: Ballistic helmet (+4), combat knife (Str+d4), commlink, HK 416 (5.56, Range 24/48/96, Damage 2d8, RoF 3, Shots 30, AP 2), HK USP (45, Range 12/24/48, Damage 2d6+1, RoF 1, Shots 12, AP 1, silencer), 2 HE grenades (Range 5/10/20, Damage 3d6, MBT, HW), night-vision goggles (no penalty for Dim or Dark Illumination), snow camo suit (+2 to Stealth in snow environment), tactical body armor (+6).

**Comment by arnonram** [comment]
Hi @stgreenb , 

sorry for the late reply, hope this will still be useful.

The issue here was  that bullet caliber at the start of the parenthesis section. For example: if you remove the 45 from the HK to be => _HK USP (Range 12/24/48, Damage 2d6+1, RoF 1, Shots 12, AP 1, silencer)_
Then it'll work.

But your issue exposed three bugs: 
1. the parser should not have failed just because it didn't know what to do with the number (i.e. 45)
2. rof was not parsed
3. shots was not parsed

Not a tough fix... it'll look like this in the end: 
![image](https://user-images.githubusercontent.com/43678762/131741077-378a8153-45c7-44a7-8458-93e7bc89c122.png)
