### ISSUE TITLE
Special Abilities will not import.

### ISSUE THREAD

**Issue by JasonSK22** [arnonram/swade-npc-importer#78]
Everything except special abilities will import.  
I've tried directly out of a PDF, editing the stat block in Notepad ++, adding @ before each special ability with no luck. Adding • to each SA.  I am not sure what is going wrong.

**Comment by arnonram** [comment]
hi @JasonSK22 ,
==> For importing edited text, see the **Modified Special Abilities** option and how to use it.

The importer was tested mainly with the core stuff, or things published by Pinnacle (deadlands, I think I even tried with Savage Pathfinder). I know some other used it with other products, but cannot guarantee. (I had trouble importing things I wrote in google docs/pdf, but since i'll not be running it soon, i did not try to understand the issue).

if you can give me an example i can try to test and figure out...

**Comment by JasonSK22** [comment]
Hi @arnonram , sorry about the delay in getting back to you.  Here is a txt file example of the npc i am trying to load up and a screen shot of the result.  The gear is wonky and I understand why.  I am really stumped on the special abilities not flowing through. 
[Overlord.txt](https://github.com/arnonram/swade-npc-importer/files/7227108/Overlord.txt)
![Overlord](https://user-images.githubusercontent.com/28511333/134706990-2b9040b7-5ff5-4dfd-83b2-8a2d84c1eac7.png)

**Comment by arnonram** [comment]
@JasonSK22 
Hmm... i'm actually having a different experience.... probably something i did...
**_Can you please check with the latest release_**

- **Special Abilities** are imported correctly
- The **Gear** is all messed up for several reasons: 
  - because the importer splits the gear line with each comma - unless they are in parenthesis, in which case it takes the whole parenthesis as a whole and tried to identify what's there (damage, armor bonus, range, etc..)
  - the Power Armor has parenthesis, but it cannot identify it as an armor/weapon so it just drops it out
  - same for the Police forces... line

![image](https://user-images.githubusercontent.com/43678762/134711750-e02f1e73-9d9a-429c-bf75-0927521b905a.png)

**Comment by JasonSK22** [comment]
Super strange.  I can get the SA to load in a test world with minimal modules but not in my rifts game world.  I am going to start removing modules and see what is causing the issue.  Thanks for your help.  Ill circle back and let you know if I find out what the problem module is.

**Comment by JasonSK22** [comment]
I keep getting this error
![Snag_44e43b](https://user-images.githubusercontent.com/28511333/134758520-6e20f150-5a82-4b98-8e28-cd38c0cf05ea.png)

**Comment by arnonram** [comment]
This one is due to this line:  
> Armored Hide: Neuron Beasts have +16 MDC Armor and +8 Toughness.

In the official stuff, it's written something like this:
> Armor +4: Scaly Hide 

The importer searches for the Armor Bonus in the first part (for example, Armor +4) 

It's fiddly, i know...

**Comment by arnonram** [comment]
implementing imports for sources not consistent with Pinnacle guidelines will not happen (by me)
