### ISSUE TITLE
Importer does not use predefined Special Ability on import

### ISSUE THREAD

**Issue by arnonram** [arnonram/swade-npc-importer#81]
Occured once again on 0.1.10; seen it with Size, likely happens on others as usual.

_Originally posted by @SalieriC in https://github.com/arnonram/swade-npc-importer/issues/73#issuecomment-952074734_

**Comment by SalieriC** [comment]
Does not happen with burrow.

**Comment by SalieriC** [comment]
However it **does** happen with Fear.

**Comment by arnonram** [comment]
@SalieriC do you mean that if you have a Special Ability item it is not added to the imported character?

i cannot seem to reproduce it..

**Comment by SalieriC** [comment]
I tried to reopen and eventually commented on the closed ticket because I feel like this keeps raising the same questions over and over again. ^^'
Take this for example (the huge in parenthesis doesn't make the difference):
![image](https://user-images.githubusercontent.com/1230041/141493178-1fb83926-29b7-45b2-a483-a5536fa14b22.png)
The importer should use the item `size` from the compendium and update it on import. But instead it's creating a new item, not using any of the data from the existing one.

**Comment by arnonram** [comment]
ahh... the + sign before the number was giving me trouble. I believe in the style guide they only add a sign for negative numbers...

**Comment by SalieriC** [comment]
You're right but it's not working with negative values as well.

**Comment by arnonram** [comment]
Tested my fix and it looks like to work well for all kinds..

**Comment by SalieriC** [comment]
Yes, tested with the version on the 0.1.11 branch and it seems to be working great.

**Comment by SalieriC** [comment]
I must take this back unfortunately. I tried importing a creature with `Size –2 (Small)` and the importer did not use the predefined item from the compendium.

**Comment by arnonram** [comment]
ok, think i got it this time
