### ISSUE TITLE
Problems with importing of predefined Items

### ISSUE THREAD

**Issue by SalieriC** [arnonram/swade-npc-importer#83]
Active Effects on Items are not applied when the importer uses a predefined item. Additional Stats do not remain on the items and locations of armor are overwritten.

Related issue: #81

**Comment by arnonram** [comment]
think i got it all.

But, importing Armor from the Core Rules compendium is tricky due to the way they write it -- for example: **_Corselet (Plate Mail)_** -- and due to the way NPC importer deals with parenthesis in the stat block, For gear, in parenthesis i  search for weapon, armor, shield property and ignore anything else.... 

So it's a mess at the moment...
